# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Flutter web app to Azure Web App - habeba

on:
  push:
    branches:
      - production
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Java
        uses: actions/setup-java@v3.12.0
        with:
          distribution: 'oracle'
          java-version: '17'

      - name: Install Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'
          channel: 'stable'

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Build Flutter web app
        run: flutter build web --release

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: flutter-web-app
          path: build/web  # Uploads the built web files

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: flutter-web-app
          path: ./flutter-web-app  # Explicitly downloads to ./flutter-web-app directory

      - name: Verify Downloaded Artifact
        run: dir ./flutter-web-app  # Checks that the artifact is successfully downloaded and lists contents

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'habeba'  # Replace with your Azure Web App name
          package: ./flutter-web-app  # Specifies the correct path for deployment
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
